name: DL
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - rich=13.9.4
  - ipywidgets=8.1.5
  - pip=25.0
  - notebook
  - pytorch-cuda
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - pandas
  - huggingface_hub
  - matplotlib
  - transformers
  - pip:
      - -r requirements.txt
