defaults:
  - model: mlp
  - data: mnist
  - optimizer: adam
  - logger: tensorboard
  - trainer: default
  - train: default
  - infer: default
  - eval: default

seed: 42

hydra:
  job:
    chdir: true
  run:
    dir: ../outputs/${hydra.job.name}/${now:%Y-%m-%dT%H-%M-%S}
  sweep:
    dir: ../outputs/${hydra.job.name}/${now:%Y-%m-%dT%H-%M-%S}
    subdir: ${hydra.job.override_dirname}