version: 1
formatters:
  plain:
    format: "%(asctime)s\t[%(levelname)s]\t--\t%(filename)s:%(lineno)s\t--\t%(message)s"
  json:
    format: "%(timestamp)s\t[%(levelname)s]\t--\t%(filename)s:%(lineno)s\t--\t%(message)s"
    class: reconplogger.JsonFormatter
handlers:
  plain_handler:
    class: logging.StreamHandler
    formatter: plain
    level: WARNING
  json_handler:
    class: logging.StreamHandler
    formatter: json
    level: WARNING
  null_handler:
    class: logging.NullHandler
loggers:
  plain_logger:
    level: DEBUG
    handlers:
      - plain_handler
  json_logger:
    level: DEBUG
    handlers:
      - json_handler
  null_logger:
    handlers:
      - null_handler